title: Tina's project
email: tinagroshkova@gmail.com
description: This is my first big project
baseurl: "/my-project"
url: ""
twitter_username: tinagroshkova
github_username:  tinagroshkova
destination: docs

plugins:
  - jekyll-feed

exclude:
  - docs
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
